[package]
name = "otis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
copypasta = "0.7.1"
regex = "1"
clap = { version = "3.1", features = ["derive"] }
chrono = "0.4"
clipboard-master = "3.1.3"